name: x00193212_CI_CD_Pipeline
env:
  AZURE_WEBAPP_NAME: 'BPCalculatorX3212'            ## set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'  
  NUGET_VERSION: '6.0.x'
on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .net 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build Project for release
        run: dotnet build --configuration release

      - name: Analyze code with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./BPCalculator
          args: >
            -Dsonar.organization=X00193212
            -Dsonar.projectKey=X00193212_myBP
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
            -Dsonar.exclusions=bin/**
            -Dsonar.exclusions=obj/**
            -Dsonar.exclusions=Pages/**
            -Dsonar.exclusions=Properties/**
            -Dsonar.exclusions=wwwroot/**
            -Dsonar.inclusions=BPCalculator.cs
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run xunit unit tests
        run: dotnet test BP.Tests/BP.Tests.csproj

      - name: Run BDD unit tests
        run:  dotnet test UnitTestsBDD/UnitTestsBDD.csproj 

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BPCalculatorX3212'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
