
name: Selenium tests

on:
  workflow_dispatch:                                # manually triggered

jobs:
  install_chrome_and_selenium_test:
    name : Install Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - uses: actions/checkout@v2
      - name: Setup .net 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build Project for release
        run: dotnet build --configuration release

      - name: Run BDD unit tests
        run:  dotnet test SeleniumTest/SelemiumTest.csproj    
